### ISSUE TITLE
发送消息失败

### ISSUE THREAD

**Issue by guaipobabys** [WangCharlie/SmartQQ#2]
登录的时候 SmartQQClient 下的
 public static ISmartQQClientBuilder Login(Action<byte[]> action, Func<string, LoginResult> json)
方法，json默认是为null，会影响消息发送吗？我的消息发送出去。

**Comment by charliewwdev** [comment]
json是需要加载的用户信息 免登陆用的  这个你扫码登陆即代表成功了

**Comment by charliewwdev** [comment]
over
