### ISSUE TITLE
windows下运行不了

### ISSUE THREAD

**Issue by ntfox0001** [WangCharlie/SmartQQ#4]
能编译通过，但是 运行到
        private LoginResult Login(Func<string, LoginResult> json)
        { 
           return Login(json);  
        }
堆栈溢出了，貌似是自己调用自己了

**Comment by ntfox0001** [comment]
可以了，代码里调用了2次start，把第二个去掉就好了，但是现在不能发消息，会提示100001错误

**Comment by charliewwdev** [comment]
检查一下协议

**Comment by cyj100** [comment]
这个不知道怎么检查了，应该是某个参数出现错误导致的。但不知道是啥参数出错？！也不知该怎么调试，用postman可以吗？

**Comment by charliewwdev** [comment]
@cyj100 用fiddler

**Comment by charliewwdev** [comment]
over
